-- 020_game_expansion_content.sql
-- Auto-generated by .arena-scratch/build_migration.cjs (see ARENA_GAME_EXPANSION_PLAN.md).
-- 46 new challenges, all seeded active=false for review before going live.
-- Breakdown: code_duel 16, bug_hunt_code 10, regex_duel 6, css_battle 6, url_submit 8.

-- Allow the new regex_duel engine
ALTER TABLE arena_challenges DROP CONSTRAINT IF EXISTS arena_challenges_challenge_type_check;
ALTER TABLE arena_challenges ADD CONSTRAINT arena_challenges_challenge_type_check
  CHECK (challenge_type IN ('url_submit','code_duel','css_battle','bug_hunt_code','regex_duel'));

INSERT INTO arena_challenges
  (slug, title, description, mode, challenge_type, difficulty, time_limit_mins, language, starter_code, solution_code, test_cases, reference_url, active)
VALUES
  ($c$reverse-string$c$, $c$Reverse a String$c$, $c$Write a function `reverseString(s)` that takes a string and returns it reversed.
For example, `reverseString("hello")` returns `"olleh"`.
Handle the empty string case.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function reverseString(s) {
  // Your code here
}$c$, $c$function reverseString(s) {
  return s.split("").reverse().join("");
}$c$, $j$[{"label":"basic word","input":"\"hello\"","expected":"\"olleh\""},{"label":"palindrome","input":"\"racecar\"","expected":"\"racecar\""},{"label":"single char","input":"\"a\"","expected":"\"a\""},{"label":"empty string","input":"\"\"","expected":"\"\""},{"label":"with spaces","input":"\"a b c\"","expected":"\"c b a\""},{"label":"numeric string","input":"\"12345\"","expected":"\"54321\""}]$j$::jsonb, NULL, false),
  ($c$sum-array$c$, $c$Sum an Array$c$, $c$Write a function `sumArray(arr)` that returns the sum of all numbers in `arr`.
Return `0` for an empty array.
All elements are finite numbers.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function sumArray(arr) {
  // Your code here
}$c$, $c$function sumArray(arr) {
  return arr.reduce(function(acc, n) { return acc + n; }, 0);
}$c$, $j$[{"label":"basic","input":"[1,2,3,4,5]","expected":"15"},{"label":"empty array","input":"[]","expected":"0"},{"label":"single element","input":"[7]","expected":"7"},{"label":"all negatives","input":"[-1,-2,-3]","expected":"-6"},{"label":"mixed sign","input":"[-5,10,-3,8]","expected":"10"},{"label":"floats","input":"[1.5,2.5]","expected":"4"}]$j$::jsonb, NULL, false),
  ($c$count-vowels$c$, $c$Count Vowels$c$, $c$Write a function `countVowels(s)` that counts the number of vowel characters (a, e, i, o, u — case-insensitive) in the string `s`.
Return an integer.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function countVowels(s) {
  // Your code here
}$c$, $c$function countVowels(s) {
  return (s.match(/[aeiou]/gi) || []).length;
}$c$, $j$[{"label":"basic sentence","input":"\"hello world\"","expected":"3"},{"label":"all vowels","input":"\"aeiou\"","expected":"5"},{"label":"no vowels","input":"\"gym\"","expected":"0"},{"label":"empty string","input":"\"\"","expected":"0"},{"label":"mixed case","input":"\"AEIgUo\"","expected":"5"},{"label":"single vowel","input":"\"a\"","expected":"1"}]$j$::jsonb, NULL, false),
  ($c$chunk-array$c$, $c$Chunk Array$c$, $c$Write a function `chunk(arr, size)` that splits `arr` into sub-arrays of length `size`.
The last chunk may be smaller if the array does not divide evenly.
Return an array of arrays.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function chunk(arr, size) {
  // Your code here
}$c$, $c$function chunk(arr, size) {
  var result = [];
  for (var i = 0; i < arr.length; i += size) {
    result.push(arr.slice(i, i + size));
  }
  return result;
}$c$, $j$[{"label":"even split","input":"[1,2,3,4], 2","expected":"[[1,2],[3,4]]"},{"label":"uneven split","input":"[1,2,3,4,5], 2","expected":"[[1,2],[3,4],[5]]"},{"label":"size equals length","input":"[1,2,3], 3","expected":"[[1,2,3]]"},{"label":"size of 1","input":"[1,2,3], 1","expected":"[[1],[2],[3]]"},{"label":"empty array","input":"[], 2","expected":"[]"},{"label":"size larger than arr","input":"[1,2], 5","expected":"[[1,2]]"}]$j$::jsonb, NULL, false),
  ($c$flatten-one-level$c$, $c$Flatten One Level$c$, $c$Write a function `flattenOne(arr)` that flattens `arr` exactly one level deep.
Nested arrays deeper than one level remain as-is.
Return the flattened array.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function flattenOne(arr) {
  // Your code here
}$c$, $c$function flattenOne(arr) {
  var result = [];
  for (var i = 0; i < arr.length; i++) {
    if (Array.isArray(arr[i])) {
      for (var j = 0; j < arr[i].length; j++) result.push(arr[i][j]);
    } else {
      result.push(arr[i]);
    }
  }
  return result;
}$c$, $j$[{"label":"basic nested","input":"[[1,2],[3,4]]","expected":"[1,2,3,4]"},{"label":"mixed flat+nested","input":"[[1,2],3,[4,5]]","expected":"[1,2,3,4,5]"},{"label":"empty subarrays","input":"[[],[1],[]]","expected":"[1]"},{"label":"already flat","input":"[1,2,3]","expected":"[1,2,3]"},{"label":"empty array","input":"[]","expected":"[]"},{"label":"deep stays nested","input":"[[1,[2,3]],4]","expected":"[1,[2,3],4]"}]$j$::jsonb, NULL, false),
  ($c$is-palindrome$c$, $c$Is Palindrome$c$, $c$Write a function `isPalindrome(s)` that returns `true` if `s` reads the same forwards and backwards, ignoring non-alphanumeric characters and case.
Return `false` otherwise.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function isPalindrome(s) {
  // Your code here
}$c$, $c$function isPalindrome(s) {
  var clean = s.toLowerCase().replace(/[^a-z0-9]/g, "");
  return clean === clean.split("").reverse().join("");
}$c$, $j$[{"label":"true basic","input":"\"racecar\"","expected":"true"},{"label":"false basic","input":"\"hello\"","expected":"false"},{"label":"spaces and punctuation","input":"\"A man a plan a canal Panama\"","expected":"true"},{"label":"single char","input":"\"a\"","expected":"true"},{"label":"empty string","input":"\"\"","expected":"true"},{"label":"mixed case palindrome","input":"\"RaceCar\"","expected":"true"},{"label":"two different chars","input":"\"ab\"","expected":"false"}]$j$::jsonb, NULL, false),
  ($c$two-sum$c$, $c$Two Sum$c$, $c$Write a function `twoSum(nums, target)` that returns the indices `[i, j]` (with `i < j`) of the two numbers in `nums` that add up to `target`.
Exactly one solution is guaranteed.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function twoSum(nums, target) {
  // Your code here
}$c$, $c$function twoSum(nums, target) {
  var map = {};
  for (var i = 0; i < nums.length; i++) {
    var complement = target - nums[i];
    if (map[complement] !== undefined) return [map[complement], i];
    map[nums[i]] = i;
  }
}$c$, $j$[{"label":"basic","input":"[2,7,11,15], 9","expected":"[0,1]"},{"label":"non-adjacent","input":"[3,2,4], 6","expected":"[1,2]"},{"label":"duplicates","input":"[3,3], 6","expected":"[0,1]"},{"label":"larger array","input":"[1,2,3,4,5,6], 9","expected":"[3,4]"},{"label":"negatives","input":"[-1,-2,-3,-4,-5], -8","expected":"[2,4]"},{"label":"zero pair","input":"[-3,4,3,90], 0","expected":"[0,2]"}]$j$::jsonb, NULL, false),
  ($c$valid-parentheses$c$, $c$Valid Parentheses$c$, $c$Write a function `isValid(s)` that determines if the input string `s` — containing only `(`, `)`, `{`, `}`, `[`, `]` — has every open bracket closed by the same type in the correct order.
Return a boolean.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function isValid(s) {
  // Your code here
}$c$, $c$function isValid(s) {
  var stack = [];
  var map = { ")": "(", "}": "{", "]": "[" };
  for (var i = 0; i < s.length; i++) {
    var c = s[i];
    if (c === "(" || c === "{" || c === "[") {
      stack.push(c);
    } else {
      if (stack.pop() !== map[c]) return false;
    }
  }
  return stack.length === 0;
}$c$, $j$[{"label":"simple parens valid","input":"\"()\"","expected":"true"},{"label":"all types valid","input":"\"()[]{}\"","expected":"true"},{"label":"mismatched","input":"\"(]\"","expected":"false"},{"label":"interleaved invalid","input":"\"([)]\"","expected":"false"},{"label":"nested valid","input":"\"{[]}\"","expected":"true"},{"label":"empty string","input":"\"\"","expected":"true"},{"label":"unclosed","input":"\"(((\"","expected":"false"}]$j$::jsonb, NULL, false),
  ($c$roman-to-int$c$, $c$Roman to Integer$c$, $c$Write a function `romanToInt(s)` that converts a Roman numeral string to an integer.
Symbols: I=1, V=5, X=10, L=50, C=100, D=500, M=1000.
Subtraction rules apply (IV=4, IX=9, XL=40, XC=90, CD=400, CM=900).$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function romanToInt(s) {
  // Your code here
}$c$, $c$function romanToInt(s) {
  var val = { I:1, V:5, X:10, L:50, C:100, D:500, M:1000 };
  var total = 0;
  for (var i = 0; i < s.length; i++) {
    var curr = val[s[i]];
    var next = val[s[i+1]] || 0;
    total += curr < next ? -curr : curr;
  }
  return total;
}$c$, $j$[{"label":"III","input":"\"III\"","expected":"3"},{"label":"IV","input":"\"IV\"","expected":"4"},{"label":"IX","input":"\"IX\"","expected":"9"},{"label":"LVIII","input":"\"LVIII\"","expected":"58"},{"label":"MCMXCIV","input":"\"MCMXCIV\"","expected":"1994"},{"label":"M","input":"\"M\"","expected":"1000"},{"label":"XL","input":"\"XL\"","expected":"40"}]$j$::jsonb, NULL, false),
  ($c$capitalize-words$c$, $c$Capitalize Words$c$, $c$Write a function `capitalizeWords(s)` that capitalizes the first letter of every word in `s` and lowercases the rest of each word.
Words are separated by single spaces.
Return the resulting string.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function capitalizeWords(s) {
  // Your code here
}$c$, $c$function capitalizeWords(s) {
  return s.split(" ").map(function(w) {
    return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
  }).join(" ");
}$c$, $j$[{"label":"basic sentence","input":"\"hello world\"","expected":"\"Hello World\""},{"label":"already capitalized","input":"\"Hello World\"","expected":"\"Hello World\""},{"label":"all caps","input":"\"HELLO WORLD\"","expected":"\"Hello World\""},{"label":"single word","input":"\"foo\"","expected":"\"Foo\""},{"label":"mixed case words","input":"\"hElLo wOrLd\"","expected":"\"Hello World\""},{"label":"empty string","input":"\"\"","expected":"\"\""}]$j$::jsonb, NULL, false),
  ($c$deep-flatten$c$, $c$Deep Flatten$c$, $c$Write a function `deepFlatten(arr)` that recursively flattens a nested array of any depth into a single flat array.
Return the flat array.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function deepFlatten(arr) {
  // Your code here
}$c$, $c$function deepFlatten(arr) {
  var result = [];
  function walk(a) {
    for (var i = 0; i < a.length; i++) {
      if (Array.isArray(a[i])) walk(a[i]);
      else result.push(a[i]);
    }
  }
  walk(arr);
  return result;
}$c$, $j$[{"label":"one level","input":"[[1,2],[3,4]]","expected":"[1,2,3,4]"},{"label":"deeply nested","input":"[1,[2,[3,[4,[5]]]]]","expected":"[1,2,3,4,5]"},{"label":"already flat","input":"[1,2,3]","expected":"[1,2,3]"},{"label":"empty array","input":"[]","expected":"[]"},{"label":"mixed depth","input":"[[1,2],[3,[4,[5,6]]],7]","expected":"[1,2,3,4,5,6,7]"},{"label":"single nested","input":"[[[[42]]]]","expected":"[42]"}]$j$::jsonb, NULL, false),
  ($c$group-by$c$, $c$Group By Key$c$, $c$Write a function `groupBy(arr, fn)` that groups elements of `arr` by the return value of `fn(element)`.
Return an object whose keys are the group keys and values are arrays of elements in insertion order.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function groupBy(arr, fn) {
  // Your code here
}$c$, $c$function groupBy(arr, fn) {
  return arr.reduce(function(acc, item) {
    var key = fn(item);
    if (!acc[key]) acc[key] = [];
    acc[key].push(item);
    return acc;
  }, {});
}$c$, $j$[{"label":"group by parity","input":"[1,2,3,4,5,6], function(x){ return x % 2 === 0 ? \"even\" : \"odd\"; }","expected":"{\"odd\":[1,3,5],\"even\":[2,4,6]}"},{"label":"group strings by first char","input":"[\"ant\",\"ape\",\"bee\",\"bat\"], function(s){ return s[0]; }","expected":"{\"a\":[\"ant\",\"ape\"],\"b\":[\"bee\",\"bat\"]}"},{"label":"single element","input":"[42], function(x){ return x > 10 ? \"big\" : \"small\"; }","expected":"{\"big\":[42]}"},{"label":"empty array","input":"[], function(x){ return x; }","expected":"{}"},{"label":"all same key","input":"[1,2,3], function(x){ return \"all\"; }","expected":"{\"all\":[1,2,3]}"},{"label":"group by string length","input":"[\"a\",\"bb\",\"cc\",\"ddd\"], function(s){ return s.length; }","expected":"{\"1\":[\"a\"],\"2\":[\"bb\",\"cc\"],\"3\":[\"ddd\"]}"}]$j$::jsonb, NULL, false),
  ($c$binary-search$c$, $c$Binary Search$c$, $c$Write a function `binarySearch(arr, target)` that searches a sorted array for `target` and returns its index, or `-1` if not found.
Use an iterative binary search. O(log n) expected.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function binarySearch(arr, target) {
  // Your code here
}$c$, $c$function binarySearch(arr, target) {
  var lo = 0, hi = arr.length - 1;
  while (lo <= hi) {
    var mid = (lo + hi) >> 1;
    if (arr[mid] === target) return mid;
    if (arr[mid] < target) lo = mid + 1;
    else hi = mid - 1;
  }
  return -1;
}$c$, $j$[{"label":"found middle","input":"[1,2,3,4,5], 3","expected":"2"},{"label":"found first","input":"[1,2,3,4,5], 1","expected":"0"},{"label":"found last","input":"[1,2,3,4,5], 5","expected":"4"},{"label":"not found","input":"[1,2,3,4,5], 6","expected":"-1"},{"label":"single element found","input":"[7], 7","expected":"0"},{"label":"single element missing","input":"[7], 3","expected":"-1"},{"label":"empty array","input":"[], 5","expected":"-1"}]$j$::jsonb, NULL, false),
  ($c$longest-substring-no-repeat$c$, $c$Longest Substring Without Repeating$c$, $c$Write a function `lengthOfLongestSubstring(s)` that returns the length of the longest substring of `s` with no repeating characters.
Use a sliding window approach.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function lengthOfLongestSubstring(s) {
  // Your code here
}$c$, $c$function lengthOfLongestSubstring(s) {
  var map = {};
  var max = 0, start = 0;
  for (var i = 0; i < s.length; i++) {
    var c = s[i];
    if (map[c] !== undefined && map[c] >= start) {
      start = map[c] + 1;
    }
    map[c] = i;
    if (i - start + 1 > max) max = i - start + 1;
  }
  return max;
}$c$, $j$[{"label":"abcabcbb","input":"\"abcabcbb\"","expected":"3"},{"label":"all same","input":"\"bbbbb\"","expected":"1"},{"label":"pwwkew","input":"\"pwwkew\"","expected":"3"},{"label":"empty","input":"\"\"","expected":"0"},{"label":"single","input":"\"a\"","expected":"1"},{"label":"all unique","input":"\"abcdef\"","expected":"6"},{"label":"dvdf","input":"\"dvdf\"","expected":"3"}]$j$::jsonb, NULL, false),
  ($c$int-to-roman$c$, $c$Integer to Roman$c$, $c$Write a function `intToRoman(num)` that converts a positive integer (1–3999) to its Roman numeral string.
Handle all subtractive cases: IV, IX, XL, XC, CD, CM.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function intToRoman(num) {
  // Your code here
}$c$, $c$function intToRoman(num) {
  var vals = [1000,900,500,400,100,90,50,40,10,9,5,4,1];
  var syms = ["M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"];
  var result = "";
  for (var i = 0; i < vals.length; i++) {
    while (num >= vals[i]) {
      result += syms[i];
      num -= vals[i];
    }
  }
  return result;
}$c$, $j$[{"label":"3","input":"3","expected":"\"III\""},{"label":"4","input":"4","expected":"\"IV\""},{"label":"9","input":"9","expected":"\"IX\""},{"label":"58","input":"58","expected":"\"LVIII\""},{"label":"1994","input":"1994","expected":"\"MCMXCIV\""},{"label":"3999","input":"3999","expected":"\"MMMCMXCIX\""},{"label":"1","input":"1","expected":"\"I\""}]$j$::jsonb, NULL, false),
  ($c$product-except-self$c$, $c$Product of Array Except Self$c$, $c$Write a function `productExceptSelf(nums)` that returns an array where each element at index `i` is the product of all elements in `nums` except `nums[i]`.
Do not use division. O(n) time.$c$, $c$speed_build$c$, $c$code_duel$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function productExceptSelf(nums) {
  // Your code here
}$c$, $c$function productExceptSelf(nums) {
  var n = nums.length;
  var result = [];
  var i;
  for (i = 0; i < n; i++) result[i] = 1;
  var prefix = 1;
  for (i = 0; i < n; i++) {
    result[i] = prefix;
    prefix *= nums[i];
  }
  var suffix = 1;
  for (i = n - 1; i >= 0; i--) {
    result[i] *= suffix;
    suffix *= nums[i];
  }
  return result;
}$c$, $j$[{"label":"basic","input":"[1,2,3,4]","expected":"[24,12,8,6]"},{"label":"with zero","input":"[0,1,2,3]","expected":"[6,0,0,0]"},{"label":"two zeros","input":"[0,0,1,2]","expected":"[0,0,0,0]"},{"label":"two elements","input":"[3,4]","expected":"[4,3]"},{"label":"all ones","input":"[1,1,1,1]","expected":"[1,1,1,1]"},{"label":"negatives","input":"[-1,1,0,-3,3]","expected":"[0,0,9,0,0]"}]$j$::jsonb, NULL, false),
  ($c$fix-the-calculator$c$, $c$Fix the Calculator$c$, $c$The function `calculate(a, op, b)` should perform basic arithmetic: '+' adds, '-' subtracts, '*' multiplies, '/' divides. Division by zero should return null. It has 2 bugs.

Signature: calculate(a, op, b) => number | null$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function calculate(a, op, b) {
  if (op === '+') return a + b;
  if (op === '-') return a - b;
  if (op === '*') return a + b; // Bug 1: wrong operator used
  if (op === '/') {
    if (b === 0) return 0; // Bug 2: should return null, not 0
    return a / b;
  }
  return null;
}$c$, $c$function calculate(a, op, b) {
  if (op === '+') return a + b;
  if (op === '-') return a - b;
  if (op === '*') return a * b;
  if (op === '/') {
    if (b === 0) return null;
    return a / b;
  }
  return null;
}$c$, $j$[{"label":"addition","input":"10, '+', 5","expected":"15"},{"label":"subtraction","input":"10, '-', 3","expected":"7"},{"label":"multiplication","input":"4, '*', 7","expected":"28"},{"label":"division","input":"20, '/', 4","expected":"5"},{"label":"division by zero","input":"9, '/', 0","expected":"null"},{"label":"negative result","input":"3, '-', 8","expected":"-5"},{"label":"multiply by zero","input":"99, '*', 0","expected":"0"}]$j$::jsonb, NULL, false),
  ($c$fix-the-palindrome-check$c$, $c$Fix the Palindrome Check$c$, $c$The function `isPalindrome(str)` should return true if the string reads the same forwards and backwards (case-insensitive, ignoring non-alphanumeric characters). It has 2 bugs.

Signature: isPalindrome(str) => boolean$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function isPalindrome(str) {
  const cleaned = str.replace(/[^a-z0-9]/g, ''); // Bug 1: missing toLowerCase() before cleaning
  const reversed = str.split('').reverse().join(''); // Bug 2: reversing str instead of cleaned
  return cleaned === reversed;
}$c$, $c$function isPalindrome(str) {
  const cleaned = str.toLowerCase().replace(/[^a-z0-9]/g, '');
  const reversed = cleaned.split('').reverse().join('');
  return cleaned === reversed;
}$c$, $j$[{"label":"simple palindrome","input":"'racecar'","expected":"true"},{"label":"not a palindrome","input":"'hello'","expected":"false"},{"label":"with spaces and punctuation","input":"'A man, a plan, a canal: Panama'","expected":"true"},{"label":"single character","input":"'a'","expected":"true"},{"label":"empty string","input":"''","expected":"true"},{"label":"case insensitive","input":"'Madam'","expected":"true"},{"label":"numbers","input":"'12321'","expected":"true"}]$j$::jsonb, NULL, false),
  ($c$fix-the-celsius-converter$c$, $c$Fix the Celsius Converter$c$, $c$The function `celsiusToFahrenheit(c)` should convert a Celsius temperature to Fahrenheit using the formula: F = (C * 9/5) + 32. It should round the result to 1 decimal place. It has 2 bugs.

Signature: celsiusToFahrenheit(c) => number$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function celsiusToFahrenheit(c) {
  const f = (c * 5 / 9) + 32; // Bug 1: formula inverted, should be 9/5
  return Math.round(f * 10) / 100; // Bug 2: should divide by 10, not 100
}$c$, $c$function celsiusToFahrenheit(c) {
  const f = (c * 9 / 5) + 32;
  return Math.round(f * 10) / 10;
}$c$, $j$[{"label":"boiling point","input":"100","expected":"212"},{"label":"freezing point","input":"0","expected":"32"},{"label":"body temp","input":"37","expected":"98.6"},{"label":"negative celsius","input":"-40","expected":"-40"},{"label":"room temp","input":"20","expected":"68"},{"label":"below freezing","input":"-10","expected":"14"}]$j$::jsonb, NULL, false),
  ($c$fix-the-word-counter$c$, $c$Fix the Word Counter$c$, $c$The function `countWords(sentence)` should return the number of words in a string. Words are separated by one or more spaces. An empty or whitespace-only string returns 0. It has 2 bugs.

Signature: countWords(sentence) => number$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$easy$c$, 15, $c$javascript$c$, $c$function countWords(sentence) {
  const trimmed = sentence.trim();
  if (trimmed.length === 0) return 1; // Bug 1: empty/whitespace string should return 0
  return trimmed.split(' ').length; // Bug 2: splits on single space; multiple spaces create empty strings
}$c$, $c$function countWords(sentence) {
  const trimmed = sentence.trim();
  if (trimmed.length === 0) return 0;
  return trimmed.split(/\s+/).length;
}$c$, $j$[{"label":"empty string","input":"''","expected":"0"},{"label":"whitespace only","input":"'   '","expected":"0"},{"label":"single word","input":"'hello'","expected":"1"},{"label":"two words","input":"'hello world'","expected":"2"},{"label":"multiple spaces","input":"'one   two   three'","expected":"3"},{"label":"leading/trailing spaces","input":"'  hello world  '","expected":"2"},{"label":"five words","input":"'the quick brown fox jumps'","expected":"5"}]$j$::jsonb, NULL, false),
  ($c$fix-the-array-dedup$c$, $c$Fix the Array Deduplicator$c$, $c$The function `deduplicate(arr)` should return a new array with duplicate values removed, preserving the first occurrence order. It has 2 bugs.

Signature: deduplicate(arr) => array$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function deduplicate(arr) {
  const seen = {};
  const result = [];
  for (const item of arr) {
    if (!seen[item]) {
      seen[item] = true;
      result.push(item);
    } else {
      result.push(item); // Bug 1: should skip duplicates, not push them
    }
  }
  return result.reverse(); // Bug 2: should not reverse — order must be preserved
}$c$, $c$function deduplicate(arr) {
  const seen = {};
  const result = [];
  for (const item of arr) {
    if (!seen[item]) {
      seen[item] = true;
      result.push(item);
    }
  }
  return result;
}$c$, $j$[{"label":"no duplicates","input":"[1, 2, 3]","expected":"[1,2,3]"},{"label":"all duplicates","input":"[1, 1, 1]","expected":"[1]"},{"label":"mixed","input":"[1, 2, 2, 3, 1, 4]","expected":"[1,2,3,4]"},{"label":"empty array","input":"[]","expected":"[]"},{"label":"preserves order","input":"[3, 1, 2, 1, 3]","expected":"[3,1,2]"},{"label":"two dupes at end","input":"[1, 2, 3, 3, 2]","expected":"[1,2,3]"}]$j$::jsonb, NULL, false),
  ($c$fix-the-email-validator$c$, $c$Fix the Email Validator$c$, $c$The function `isValidEmail(email)` should return true if the email has exactly one '@', a non-empty local part, a non-empty domain with at least one dot, and a TLD of at least 2 characters. It has 2 bugs.

Signature: isValidEmail(email) => boolean$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function isValidEmail(email) {
  if (!email || typeof email !== 'string') return false;
  const parts = email.split('@');
  if (parts.length !== 2) return false;
  const [local, domain] = parts;
  if (local.length === 0) return false;
  const domainParts = domain.split('.');
  if (domainParts.length < 2) return false;
  const tld = domainParts[domainParts.length - 1];
  if (tld.length < 1) return false; // Bug 1: TLD must be at least 2 chars, not 1
  const domainBody = domainParts.slice(0, -1).join('.');
  if (domainBody.length === 0) return true; // Bug 2: empty domain body should return false
  return true;
}$c$, $c$function isValidEmail(email) {
  if (!email || typeof email !== 'string') return false;
  const parts = email.split('@');
  if (parts.length !== 2) return false;
  const [local, domain] = parts;
  if (local.length === 0) return false;
  const domainParts = domain.split('.');
  if (domainParts.length < 2) return false;
  const tld = domainParts[domainParts.length - 1];
  if (tld.length < 2) return false;
  const domainBody = domainParts.slice(0, -1).join('.');
  if (domainBody.length === 0) return false;
  return true;
}$c$, $j$[{"label":"valid email","input":"'user@example.com'","expected":"true"},{"label":"no at sign","input":"'userexample.com'","expected":"false"},{"label":"two at signs","input":"'user@@example.com'","expected":"false"},{"label":"empty local part","input":"'@example.com'","expected":"false"},{"label":"short TLD (1 char)","input":"'user@example.c'","expected":"false"},{"label":"missing domain body","input":"'user@.com'","expected":"false"},{"label":"valid subdomain","input":"'user@mail.example.co.uk'","expected":"true"}]$j$::jsonb, NULL, false),
  ($c$fix-the-flatten$c$, $c$Fix the Array Flattener$c$, $c$The function `flattenOne(arr)` should flatten an array exactly one level deep. Nested arrays at the second level are left as-is (not flattened further). It has 2 bugs.

Signature: flattenOne(arr) => array$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function flattenOne(arr) {
  const result = [];
  for (const item of arr) {
    if (Array.isArray(item)) {
      for (const inner of item) {
        result.push(inner);
        if (Array.isArray(inner)) { // Bug 1: extra recursion — one-level flatten should stop here
          for (const deep of inner) result.push(deep);
        }
      }
    } else {
      result.push(item);
    }
  }
  return result.slice(1); // Bug 2: slice(1) drops the first element
}$c$, $c$function flattenOne(arr) {
  const result = [];
  for (const item of arr) {
    if (Array.isArray(item)) {
      for (const inner of item) {
        result.push(inner);
      }
    } else {
      result.push(item);
    }
  }
  return result;
}$c$, $j$[{"label":"already flat","input":"[1, 2, 3]","expected":"[1,2,3]"},{"label":"one level nested","input":"[[1, 2], [3, 4]]","expected":"[1,2,3,4]"},{"label":"mixed flat and nested","input":"[1, [2, 3], 4]","expected":"[1,2,3,4]"},{"label":"deeply nested stays nested","input":"[[1, [2, 3]], 4]","expected":"[1,[2,3],4]"},{"label":"empty array","input":"[]","expected":"[]"},{"label":"nested empty arrays","input":"[[], [1], []]","expected":"[1]"}]$j$::jsonb, NULL, false),
  ($c$fix-the-chunk$c$, $c$Fix the Array Chunker$c$, $c$The function `chunk(arr, size)` should split an array into groups of `size`. The last group may be smaller. If `size <= 0` return `[]`. An empty array returns `[]`. It has 2 bugs.

Signature: chunk(arr, size) => array of arrays$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$medium$c$, 20, $c$javascript$c$, $c$function chunk(arr, size) {
  if (size <= 0) return null; // Bug 1: should return [], not null
  if (arr.length === 0) return [];
  const result = [];
  for (let i = 0; i < arr.length; i += size) {
    result.push(arr.slice(i, i + size - 1)); // Bug 2: off-by-one, should be i + size
  }
  return result;
}$c$, $c$function chunk(arr, size) {
  if (size <= 0) return [];
  if (arr.length === 0) return [];
  const result = [];
  for (let i = 0; i < arr.length; i += size) {
    result.push(arr.slice(i, i + size));
  }
  return result;
}$c$, $j$[{"label":"even chunks","input":"[1, 2, 3, 4], 2","expected":"[[1,2],[3,4]]"},{"label":"uneven last chunk","input":"[1, 2, 3, 4, 5], 2","expected":"[[1,2],[3,4],[5]]"},{"label":"size larger than array","input":"[1, 2, 3], 5","expected":"[[1,2,3]]"},{"label":"size of 1","input":"[1, 2, 3], 1","expected":"[[1],[2],[3]]"},{"label":"empty array","input":"[], 3","expected":"[]"},{"label":"invalid size zero","input":"[1, 2, 3], 0","expected":"[]"},{"label":"chunk of 3","input":"[1, 2, 3, 4, 5, 6], 3","expected":"[[1,2,3],[4,5,6]]"}]$j$::jsonb, NULL, false),
  ($c$fix-the-recursive-sum$c$, $c$Fix the Recursive Sum$c$, $c$The function `sumNested(val)` recursively sums all numbers in a deeply nested array. Numbers are summed directly; arrays are recursed into; anything else is ignored (treated as 0). It has 3 bugs.

Signature: sumNested(val) => number$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function sumNested(val) {
  if (typeof val === 'number') return val;
  if (Array.isArray(val)) {
    let total = 1; // Bug 1: should start at 0, not 1
    for (const item of val) {
      total = total + sumNested(item); // Bug 2: should use += not reassignment (actually fine) — real bug: multiplies instead of adds below
    }
    return total;
  }
  return 1; // Bug 3: non-number non-array should return 0, not 1
}$c$, $c$function sumNested(val) {
  if (typeof val === 'number') return val;
  if (Array.isArray(val)) {
    let total = 0;
    for (const item of val) {
      total = total + sumNested(item);
    }
    return total;
  }
  return 0;
}$c$, $j$[{"label":"single number","input":"5","expected":"5"},{"label":"flat array","input":"[1, 2, 3]","expected":"6"},{"label":"nested array","input":"[1, [2, 3], [4, [5]]]","expected":"15"},{"label":"empty array","input":"[]","expected":"0"},{"label":"ignore non-numbers","input":"[1, 'x', 2, null, 3]","expected":"6"},{"label":"deeply nested","input":"[[1, [2, [3, [4]]]], 5]","expected":"15"},{"label":"all non-numbers","input":"['a', 'b', null]","expected":"0"}]$j$::jsonb, NULL, false),
  ($c$fix-the-state-machine$c$, $c$Fix the Traffic Light State Machine$c$, $c$The function `nextLight(current)` implements a traffic light cycle: 'red' -> 'green' -> 'yellow' -> 'red'. It should return the next state string. For an unknown state it returns null. It has 2 bugs.

Signature: nextLight(current) => string | null$c$, $c$bug_hunt$c$, $c$bug_hunt_code$c$, $c$hard$c$, 30, $c$javascript$c$, $c$function nextLight(current) {
  const transitions = {
    red: 'green',
    green: 'red', // Bug 1: should transition to 'yellow', not back to 'red'
    yellow: 'red',
  };
  if (!transitions.hasOwnProperty(current)) return undefined; // Bug 2: should return null
  return transitions[current];
}$c$, $c$function nextLight(current) {
  const transitions = {
    red: 'green',
    green: 'yellow',
    yellow: 'red',
  };
  if (!transitions.hasOwnProperty(current)) return null;
  return transitions[current];
}$c$, $j$[{"label":"red to green","input":"'red'","expected":"\"green\""},{"label":"green to yellow","input":"'green'","expected":"\"yellow\""},{"label":"yellow to red","input":"'yellow'","expected":"\"red\""},{"label":"unknown state","input":"'purple'","expected":"null"},{"label":"empty string","input":"''","expected":"null"},{"label":"full cycle start","input":"'red'","expected":"\"green\""},{"label":"case sensitive","input":"'Red'","expected":"null"}]$j$::jsonb, NULL, false),
  ($c$regex-email-basic$c$, $c$Match an Email$c$, $c$Write a regex that matches well-formed email addresses and rejects malformed ones.

An address is: one-or-more non-space, non-@ characters, then @, then one-or-more non-space non-@ characters, then a dot, then a TLD.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$easy$c$, 8, $c$regex$c$, $c$$c$, $c$^[^@\s]+@[^@\s]+\.[^@\s]+$$c$, $j$[{"label":"simple address","input":"a@b.com","expected":"match"},{"label":"dotted local + multi-part domain","input":"john.doe@example.co.uk","expected":"match"},{"label":"underscores allowed","input":"x_y@z.io","expected":"match"},{"label":"no @ sign","input":"no-at.com","expected":"reject"},{"label":"no dot in domain","input":"a@b","expected":"reject"},{"label":"missing local part","input":"@b.com","expected":"reject"},{"label":"space inside","input":"a b@c.com","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$regex-hex-color$c$, $c$Hex Colour Codes$c$, $c$Match CSS hex colours: a # followed by exactly 3 or exactly 6 hexadecimal digits (0-9, a-f, A-F). Reject anything else.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$easy$c$, 8, $c$regex$c$, $c$$c$, $c$^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$$c$, $j$[{"label":"3-digit","input":"#fff","expected":"match"},{"label":"6-digit upper","input":"#FFFFFF","expected":"match"},{"label":"6-digit mixed","input":"#1a2b3c","expected":"match"},{"label":"3-digit letters","input":"#abc","expected":"match"},{"label":"no hash","input":"fff","expected":"reject"},{"label":"two digits","input":"#ff","expected":"reject"},{"label":"five digits","input":"#12345","expected":"reject"},{"label":"non-hex letter","input":"#gggggg","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$regex-time-24h$c$, $c$24-Hour Clock$c$, $c$Match valid 24-hour times in HH:MM form, from 00:00 to 23:59. Hours and minutes are always two digits. Reject out-of-range or malformed times.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$medium$c$, 10, $c$regex$c$, $c$$c$, $c$^([01][0-9]|2[0-3]):[0-5][0-9]$$c$, $j$[{"label":"midnight","input":"00:00","expected":"match"},{"label":"last minute","input":"23:59","expected":"match"},{"label":"morning","input":"09:30","expected":"match"},{"label":"afternoon","input":"13:45","expected":"match"},{"label":"hour 24","input":"24:00","expected":"reject"},{"label":"minute 60","input":"12:60","expected":"reject"},{"label":"single-digit hour","input":"9:30","expected":"reject"},{"label":"single-digit minute","input":"23:5","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$regex-url-slug$c$, $c$URL Slug$c$, $c$Match valid URL slugs: lowercase letters and digits, separated by single hyphens. No leading, trailing, or doubled hyphens. No uppercase, spaces, or underscores.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$medium$c$, 10, $c$regex$c$, $c$$c$, $c$^[a-z0-9]+(-[a-z0-9]+)*$$c$, $j$[{"label":"single word","input":"hello","expected":"match"},{"label":"two words","input":"hello-world","expected":"match"},{"label":"alnum segments","input":"a1-b2-c3","expected":"match"},{"label":"word and number","input":"post-123","expected":"match"},{"label":"uppercase","input":"Hello","expected":"reject"},{"label":"leading hyphen","input":"-hello","expected":"reject"},{"label":"trailing hyphen","input":"hello-","expected":"reject"},{"label":"double hyphen","input":"hello--world","expected":"reject"},{"label":"underscore","input":"hello_world","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$regex-ipv4$c$, $c$IPv4 Address$c$, $c$Match valid IPv4 addresses: four dot-separated octets, each 0-255 with no leading zeros (except the value 0 itself). Reject out-of-range octets or the wrong number of parts.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$hard$c$, 12, $c$regex$c$, $c$$c$, $c$^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$$c$, $j$[{"label":"all zeros","input":"0.0.0.0","expected":"match"},{"label":"broadcast","input":"255.255.255.255","expected":"match"},{"label":"private","input":"192.168.1.1","expected":"match"},{"label":"public dns","input":"8.8.8.8","expected":"match"},{"label":"octet over 255","input":"256.1.1.1","expected":"reject"},{"label":"only three octets","input":"1.1.1","expected":"reject"},{"label":"five octets","input":"1.1.1.1.1","expected":"reject"},{"label":"leading zero","input":"01.1.1.1","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$regex-camelcase$c$, $c$camelCase Identifier$c$, $c$Match camelCase identifiers: start with a lowercase letter, contain only letters and digits, and include at least one uppercase 'hump'. Reject PascalCase, all-lowercase, snake_case, and anything with spaces or leading digits.$c$, $c$speed_build$c$, $c$regex_duel$c$, $c$hard$c$, 12, $c$regex$c$, $c$$c$, $c$^[a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*$$c$, $j$[{"label":"classic camel","input":"camelCase","expected":"match"},{"label":"long camel","input":"myVariableName","expected":"match"},{"label":"two letters","input":"aB","expected":"match"},{"label":"with trailing digit","input":"getValue2","expected":"match"},{"label":"pascal case","input":"CamelCase","expected":"reject"},{"label":"all lowercase","input":"alllower","expected":"reject"},{"label":"snake case","input":"snake_case","expected":"reject"},{"label":"leading digits","input":"123abc","expected":"reject"}]$j$::jsonb, NULL, false),
  ($c$pricing-card$c$, $c$Build the Pricing Card$c$, $c$Recreate a pricing card component centred on a dark (#0a0a0f) page.
The card should have a white or near-white background (#ffffff or #f9fafb), rounded corners (at least 12px), and a drop shadow.
Inside the card: a plan name heading (e.g. 'Pro'), a large price display (e.g. '$29/mo'), a short subtitle or description line, and a prominent CTA button.
The CTA button must use the indigo colour #6366f1 as its background.
Layout is vertical/stacked, width roughly 280-340px.
Use HTML and CSS only — no JavaScript.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$easy$c$, 15, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .card { background:#ffffff; color:#111827; border-radius:16px; box-shadow:0 8px 32px rgba(0,0,0,0.5); padding:32px 28px; width:300px; display:flex; flex-direction:column; gap:12px; }
  .plan { font-size:14px; font-weight:600; text-transform:uppercase; letter-spacing:.08em; color:#6366f1; }
  .price { font-size:48px; font-weight:700; line-height:1; }
  .price span { font-size:18px; font-weight:400; color:#6b7280; }
  .desc { color:#6b7280; font-size:14px; }
  .btn { margin-top:8px; background:#6366f1; color:#fff; border:none; border-radius:8px; padding:12px; font-size:16px; font-weight:600; cursor:pointer; }
</style>
</head>
<body>
  <div class="card">
    <div class="plan">Pro</div>
    <div class="price">$29<span>/mo</span></div>
    <div class="desc">Everything you need to ship faster.</div>
    <button class="btn">Get started</button>
  </div>
</body>
</html>$c$, $j$[{"label":"has a card/container element with a light background","input":"!!(document.querySelector('[style*=\"background:#fff\"]') || document.querySelector('[style*=\"background: #fff\"]') || document.querySelector('[style*=\"background:#ffffff\"]') || document.querySelector('[style*=\"background: #ffffff\"]') || document.querySelector('[style*=\"background:#f9fafb\"]') || (()=>{ const el = document.querySelector('.card') || document.querySelector('[class]'); return el && getComputedStyle(el).backgroundColor !== 'rgba(0, 0, 0, 0)' && getComputedStyle(el).backgroundColor !== 'rgb(10, 10, 15)'; })())","expected":"\"true\""},{"label":"has a price element displaying a dollar amount","input":"document.body.innerHTML.includes('$') && (document.body.innerHTML.includes('/mo') || document.body.innerHTML.includes('/month') || document.body.innerHTML.includes('mo'))","expected":"\"true\""},{"label":"has at least one button","input":"document.querySelectorAll('button').length > 0 || document.querySelectorAll('a[class*=\"btn\"]').length > 0 || document.querySelectorAll('[role=\"button\"]').length > 0","expected":"\"true\""},{"label":"button uses indigo colour (#6366f1)","input":"document.body.innerHTML.includes('6366f1') || document.body.innerHTML.includes('99, 102, 241') || document.body.innerHTML.includes('6366F1')","expected":"\"true\""},{"label":"card has rounded corners","input":"document.body.innerHTML.includes('border-radius') || document.body.innerHTML.includes('rounded')","expected":"\"true\""},{"label":"has a plan name or heading text","input":"!!(document.querySelector('h1') || document.querySelector('h2') || document.querySelector('h3') || document.querySelector('.plan') || document.body.innerHTML.toLowerCase().includes('pro') || document.body.innerHTML.toLowerCase().includes('plan'))","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$toggle-switch$c$, $c$Build the Toggle Switch$c$, $c$Create a styled toggle switch UI centred on a dark (#0a0a0f) page.
The toggle should visually resemble a pill-shaped track (width ~48px, height ~26px) with a circular thumb inside it.
Show TWO states side by side or stacked: one toggle in the OFF state (grey track, #4b5563) and one toggle in the ON state (indigo track, #6366f1, thumb on the right).
Each toggle should have a label (e.g. 'Notifications off' / 'Notifications on') next to or below it.
Use HTML and CSS only — no JavaScript. Do not worry about interactivity.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$easy$c$, 15, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:24px; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .toggle-row { display:flex; align-items:center; gap:12px; }
  .track { width:48px; height:26px; border-radius:999px; position:relative; transition:background .2s; }
  .track.off { background:#4b5563; }
  .track.on { background:#6366f1; }
  .thumb { width:20px; height:20px; border-radius:50%; background:#fff; position:absolute; top:3px; transition:left .2s; }
  .track.off .thumb { left:3px; }
  .track.on .thumb { left:25px; }
  .label { font-size:14px; color:#d1d5db; }
</style>
</head>
<body>
  <div class="toggle-row">
    <div class="track off"><div class="thumb"></div></div>
    <span class="label">Notifications off</span>
  </div>
  <div class="toggle-row">
    <div class="track on"><div class="thumb"></div></div>
    <span class="label">Notifications on</span>
  </div>
</body>
</html>$c$, $j$[{"label":"has at least two toggle track elements","input":"(document.querySelectorAll('.track').length >= 2) || (document.querySelectorAll('[style*=\"border-radius: 999px\"]').length >= 2) || (document.querySelectorAll('[style*=\"border-radius:999px\"]').length >= 2) || (document.querySelectorAll('[style*=\"border-radius: 9999px\"]').length >= 2) || (document.querySelectorAll('input[type=\"checkbox\"]').length >= 2)","expected":"\"true\""},{"label":"has a circular thumb element","input":"!!(document.querySelector('.thumb') || document.querySelector('[style*=\"border-radius: 50%\"]') || document.querySelector('[style*=\"border-radius:50%\"]'))","expected":"\"true\""},{"label":"uses indigo colour for on-state track","input":"document.body.innerHTML.includes('6366f1') || document.body.innerHTML.includes('99, 102, 241') || document.body.innerHTML.includes('6366F1') || document.body.innerHTML.includes('indigo')","expected":"\"true\""},{"label":"uses a grey colour for the off-state track","input":"document.body.innerHTML.includes('4b5563') || document.body.innerHTML.includes('6b7280') || document.body.innerHTML.includes('9ca3af') || document.body.innerHTML.includes('gray') || document.body.innerHTML.includes('grey')","expected":"\"true\""},{"label":"has label text for the toggles","input":"document.body.innerText.trim().length > 5","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$progress-bar$c$, $c$Build the Progress Bar$c$, $c$Create a progress bar UI centred on a dark (#0a0a0f) page.
Show THREE progress bars stacked vertically, each with a label above-left and a percentage above-right.
Bar track: full width (~320px), height ~10px, background #1f2937, border-radius at least 6px.
Filled portion: uses the colour #6366f1, border-radius matching the track. The three bars should be at different fill levels (e.g. 30%, 65%, 90%).
Each bar should sit inside a small card or container (background #111827, padding ~16px, rounded ~10px).
Use HTML and CSS only — no JavaScript.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$easy$c$, 15, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:12px; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .card { background:#111827; border-radius:10px; padding:16px; width:320px; display:flex; flex-direction:column; gap:8px; }
  .meta { display:flex; justify-content:space-between; font-size:13px; color:#9ca3af; }
  .track { height:10px; background:#1f2937; border-radius:6px; overflow:hidden; }
  .fill { height:100%; background:#6366f1; border-radius:6px; }
</style>
</head>
<body>
  <div class="card">
    <div class="meta"><span>Design</span><span>30%</span></div>
    <div class="track"><div class="fill" style="width:30%"></div></div>
  </div>
  <div class="card">
    <div class="meta"><span>Development</span><span>65%</span></div>
    <div class="track"><div class="fill" style="width:65%"></div></div>
  </div>
  <div class="card">
    <div class="meta"><span>Testing</span><span>90%</span></div>
    <div class="track"><div class="fill" style="width:90%"></div></div>
  </div>
</body>
</html>$c$, $j$[{"label":"has at least three progress bar track elements","input":"(document.querySelectorAll('.track').length >= 3) || (document.querySelectorAll('[role=\"progressbar\"]').length >= 3) || (document.querySelectorAll('progress').length >= 3) || (document.querySelectorAll('.bar').length >= 3) || (document.querySelectorAll('[style*=\"height: 10px\"]').length >= 3) || (document.querySelectorAll('[style*=\"height:10px\"]').length >= 3) || (document.querySelectorAll('[style*=\"border-radius\"]').length >= 3)","expected":"\"true\""},{"label":"uses indigo fill colour","input":"document.body.innerHTML.includes('6366f1') || document.body.innerHTML.includes('99, 102, 241') || document.body.innerHTML.includes('6366F1')","expected":"\"true\""},{"label":"has percentage labels","input":"document.body.innerHTML.includes('%')","expected":"\"true\""},{"label":"bars have different fill widths","input":"(()=>{ const fills = Array.from(document.querySelectorAll('.fill, [style*=\"width:\"]')).map(el=>el.style.width).filter(w=>w&&w.includes('%')); const unique = new Set(fills); return unique.size >= 2; })()","expected":"\"true\""},{"label":"has a dark card/container background","input":"document.body.innerHTML.includes('111827') || document.body.innerHTML.includes('1f2937') || document.body.innerHTML.includes('0f172a')","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$notification-toast$c$, $c$Build the Notification Toast$c$, $c$Create a notification toast component positioned in the bottom-right corner of a dark (#0a0a0f) page.
The toast should have a dark card background (#111827), a left border accent in green (#22c55e), padding ~16px, and a border-radius of ~10px.
Inside: a green check icon or circle (you can use a simple ✓ character or a green filled circle), a bold title ('Payment successful'), a muted subtitle ('Your invoice has been sent.'), and a small dismiss button (×).
Make it position:fixed, bottom-right, with a subtle box-shadow.
Use HTML and CSS only — no JavaScript.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$easy$c$, 15, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .toast { position:fixed; bottom:24px; right:24px; background:#111827; border-left:4px solid #22c55e; border-radius:10px; padding:16px 20px; min-width:280px; box-shadow:0 8px 24px rgba(0,0,0,0.5); display:flex; align-items:flex-start; gap:12px; }
  .icon { width:24px; height:24px; border-radius:50%; background:#22c55e; display:flex; align-items:center; justify-content:center; flex-shrink:0; font-size:14px; color:#fff; font-weight:700; }
  .body { flex:1; }
  .title { font-weight:700; font-size:15px; margin-bottom:2px; }
  .sub { color:#9ca3af; font-size:13px; }
  .dismiss { background:none; border:none; color:#6b7280; font-size:18px; cursor:pointer; padding:0; line-height:1; }
</style>
</head>
<body>
  <div class="toast">
    <div class="icon">&#10003;</div>
    <div class="body">
      <div class="title">Payment successful</div>
      <div class="sub">Your invoice has been sent.</div>
    </div>
    <button class="dismiss">&times;</button>
  </div>
</body>
</html>$c$, $j$[{"label":"toast is positioned fixed or absolute in the corner","input":"!!(document.querySelector('[style*=\"position: fixed\"]') || document.querySelector('[style*=\"position:fixed\"]') || document.querySelector('.toast') || (()=>{ const el = document.querySelector('[class]'); return el && (getComputedStyle(el).position === 'fixed' || getComputedStyle(el).position === 'absolute'); })())","expected":"\"true\""},{"label":"uses green accent colour","input":"document.body.innerHTML.includes('22c55e') || document.body.innerHTML.includes('34, 197, 94') || document.body.innerHTML.includes('16a34a') || document.body.innerHTML.includes('green')","expected":"\"true\""},{"label":"has a title mentioning payment or success","input":"document.body.innerText.toLowerCase().includes('payment') || document.body.innerText.toLowerCase().includes('success') || document.body.innerText.toLowerCase().includes('sent') || document.body.innerText.toLowerCase().includes('saved')","expected":"\"true\""},{"label":"has a dismiss or close button","input":"document.querySelectorAll('button').length > 0 || document.body.innerHTML.includes('&times;') || document.body.innerHTML.includes('×') || document.body.innerHTML.includes('✕') || document.body.innerHTML.includes('close')","expected":"\"true\""},{"label":"has a left border accent","input":"document.body.innerHTML.includes('border-left') || document.body.innerHTML.includes('border-l') || document.body.innerHTML.includes('border: ') || document.body.innerHTML.includes('border:')","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$login-form$c$, $c$Build the Login Form$c$, $c$Recreate a clean login form centred on a dark (#0a0a0f) page.
The form card should have background #111827, rounded corners (~12px), padding ~32px, width ~360px.
Contents: a heading 'Welcome back', a small subtitle 'Sign in to your account', an email input, a password input, and a full-width submit button ('Sign in') in indigo (#6366f1).
Inputs should have background #1f2937, border 1px solid #374151, border-radius ~8px, and white text.
A 'Forgot password?' link in muted colour below the password field.
HTML and CSS only — no JavaScript.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$medium$c$, 20, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .card { background:#111827; border-radius:12px; padding:32px; width:360px; box-shadow:0 8px 32px rgba(0,0,0,0.5); }
  h1 { margin:0 0 4px; font-size:22px; font-weight:700; }
  .sub { color:#9ca3af; font-size:14px; margin-bottom:24px; }
  .field { display:flex; flex-direction:column; gap:6px; margin-bottom:16px; }
  label { font-size:13px; font-weight:500; color:#d1d5db; }
  input { background:#1f2937; border:1px solid #374151; border-radius:8px; padding:10px 12px; color:#fff; font-size:14px; outline:none; }
  input::placeholder { color:#6b7280; }
  .forgot { display:flex; justify-content:flex-end; margin-bottom:20px; }
  .forgot a { color:#6366f1; font-size:13px; text-decoration:none; }
  .btn { width:100%; background:#6366f1; color:#fff; border:none; border-radius:8px; padding:11px; font-size:15px; font-weight:600; cursor:pointer; }
</style>
</head>
<body>
  <div class="card">
    <h1>Welcome back</h1>
    <p class="sub">Sign in to your account</p>
    <div class="field">
      <label for="email">Email</label>
      <input type="email" id="email" placeholder="you@example.com" />
    </div>
    <div class="field">
      <label for="pw">Password</label>
      <input type="password" id="pw" placeholder="••••••••" />
    </div>
    <div class="forgot"><a href="#">Forgot password?</a></div>
    <button class="btn">Sign in</button>
  </div>
</body>
</html>$c$, $j$[{"label":"has an email input field","input":"!!(document.querySelector('input[type=\"email\"]') || document.querySelector('input[name=\"email\"]') || document.querySelector('input[placeholder*=\"email\"]') || document.querySelector('input[placeholder*=\"@\"]') || document.querySelector('input[id*=\"email\"]'))","expected":"\"true\""},{"label":"has a password input field","input":"document.querySelectorAll('input[type=\"password\"]').length > 0 || document.body.innerHTML.includes('password')","expected":"\"true\""},{"label":"has a submit button with sign-in text","input":"!!(Array.from(document.querySelectorAll('button, input[type=\"submit\"]')).find(el=>el.textContent.toLowerCase().includes('sign') || el.textContent.toLowerCase().includes('login') || el.textContent.toLowerCase().includes('log in') || el.value && (el.value.toLowerCase().includes('sign') || el.value.toLowerCase().includes('login'))))","expected":"\"true\""},{"label":"submit button uses indigo colour","input":"document.body.innerHTML.includes('6366f1') || document.body.innerHTML.includes('99, 102, 241') || document.body.innerHTML.includes('indigo')","expected":"\"true\""},{"label":"has a forgot password link or text","input":"document.body.innerText.toLowerCase().includes('forgot') || document.body.innerHTML.toLowerCase().includes('forgot')","expected":"\"true\""},{"label":"has a heading with welcome or sign-in text","input":"!!(Array.from(document.querySelectorAll('h1,h2,h3')).find(el=>el.textContent.toLowerCase().includes('welcome') || el.textContent.toLowerCase().includes('sign') || el.textContent.toLowerCase().includes('login') || el.textContent.toLowerCase().includes('log in')))","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$stat-badge-row$c$, $c$Build the Stats Badge Row$c$, $c$Create a row of three stat/badge tiles centred on a dark (#0a0a0f) page.
Each tile: background #111827, border 1px solid #1f2937, border-radius ~12px, padding ~20px 24px, min-width ~140px.
Each tile shows: a small icon emoji or symbol at the top (e.g. ⚡, 🔥, ★), a large bold stat number (e.g. '1,284', '98%', '4.9'), and a muted label below (e.g. 'Requests', 'Uptime', 'Rating').
The three tiles sit in a horizontal flex row with ~16px gap.
Stat numbers should be white and at least 28px. Labels should be muted (#9ca3af), font-size ~13px.
HTML and CSS only — no JavaScript.$c$, $c$clone_battle$c$, $c$css_battle$c$, $c$medium$c$, 20, $c$html$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  /* Your styles here */
</style>
</head>
<body>
  <!-- Your HTML here -->
</body>
</html>$c$, $c$<!DOCTYPE html>
<html>
<head>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; background:#0a0a0f; font-family:system-ui,sans-serif; color:white; }
  .row { display:flex; gap:16px; }
  .tile { background:#111827; border:1px solid #1f2937; border-radius:12px; padding:20px 24px; min-width:140px; display:flex; flex-direction:column; align-items:center; gap:8px; }
  .icon { font-size:24px; }
  .stat { font-size:32px; font-weight:700; color:#fff; line-height:1; }
  .label { font-size:13px; color:#9ca3af; }
</style>
</head>
<body>
  <div class="row">
    <div class="tile"><div class="icon">&#9889;</div><div class="stat">1,284</div><div class="label">Requests</div></div>
    <div class="tile"><div class="icon">&#128293;</div><div class="stat">98%</div><div class="label">Uptime</div></div>
    <div class="tile"><div class="icon">&#9733;</div><div class="stat">4.9</div><div class="label">Rating</div></div>
  </div>
</body>
</html>$c$, $j$[{"label":"has at least three tile/card elements","input":"(document.querySelectorAll('.tile').length >= 3) || (document.querySelectorAll('.card').length >= 3) || (document.querySelectorAll('.stat-card').length >= 3) || (()=>{ const children = document.querySelector('.row, .stats, .grid, main, body > div')?.children; return children && children.length >= 3; })()","expected":"\"true\""},{"label":"has at least three stat numbers visible in the page","input":"(()=>{ const text = document.body.innerText; const matches = text.match(/\\d[\\d,.%]+/g); return matches && matches.length >= 3; })()","expected":"\"true\""},{"label":"tiles use dark card background colour","input":"document.body.innerHTML.includes('111827') || document.body.innerHTML.includes('1a1a2e') || document.body.innerHTML.includes('0f172a') || document.body.innerHTML.includes('1e293b')","expected":"\"true\""},{"label":"has muted label text (small, grey coloured)","input":"document.body.innerHTML.includes('9ca3af') || document.body.innerHTML.includes('6b7280') || document.body.innerHTML.includes('a0aec0') || document.querySelectorAll('.label, .caption, .sub, .muted').length > 0","expected":"\"true\""},{"label":"tiles are laid out horizontally with flex or grid","input":"document.body.innerHTML.includes('display:flex') || document.body.innerHTML.includes('display: flex') || document.body.innerHTML.includes('display:grid') || document.body.innerHTML.includes('display: grid') || document.body.innerHTML.includes('flex-direction: row') || !document.body.innerHTML.includes('flex-direction: column')","expected":"\"true\""}]$j$::jsonb, NULL, false),
  ($c$pricing-page-speed-build$c$, $c$Build a SaaS Pricing Page$c$, $c$Build and deploy a responsive pricing page for a fictional SaaS product.
Include three tiers (Free, Pro, Enterprise) each with a name, monthly price, a short tagline, a bulleted feature list (4-6 items), and a CTA button.
Highlight the recommended 'Pro' tier visually (e.g. border, badge, or elevated card).
The page must be mobile-responsive, load in under 3 seconds, and achieve a Lighthouse performance score above 80.
Constraints: no heavy UI frameworks — plain HTML/CSS, Tailwind, or lightweight CSS-in-JS only.$c$, $c$speed_build$c$, $c$url_submit$c$, $c$easy$c$, 25, $c$javascript$c$, NULL, NULL, NULL, NULL, false),
  ($c$blog-index-speed-build$c$, $c$Build a Blog Index Page$c$, $c$Build and deploy a blog index page for a fictional technical blog.
The page must show at least six article cards in a responsive grid (2-3 columns on desktop, 1 on mobile).
Each card needs: a cover image (placeholder OK), title, author name with avatar, publish date, category tag, and a short excerpt.
Include a sticky header with a logo and nav links, and a footer with social links.
Aim for a Lighthouse accessibility score above 85 — all images must have alt text and interactive elements must be keyboard-accessible.$c$, $c$speed_build$c$, $c$url_submit$c$, $c$easy$c$, 25, $c$javascript$c$, NULL, NULL, NULL, NULL, false),
  ($c$analytics-dashboard-speed-build$c$, $c$Build an Analytics Dashboard$c$, $c$Build and deploy a front-end analytics dashboard for a fictional web app.
Required sections: a top stats row (4 KPI cards — e.g. users, sessions, bounce rate, revenue), a large chart area (use a lightweight chart library such as Chart.js or Recharts — a static SVG approximation is acceptable), a recent-activity table with at least 8 rows, and a sidebar navigation.
The layout must be a two-column sidebar + main-content structure on desktop.
Data can be fully hardcoded. Lighthouse performance must stay above 75.$c$, $c$speed_build$c$, $c$url_submit$c$, $c$medium$c$, 40, $c$javascript$c$, NULL, NULL, NULL, NULL, false),
  ($c$restaurant-menu-speed-build$c$, $c$Build a Restaurant Menu Page$c$, $c$Build and deploy a restaurant menu page for a fictional restaurant.
The page must have: a hero section with the restaurant name, a tagline, and a background image; sticky tab navigation for at least three menu categories (e.g. Starters, Mains, Desserts); item cards within each category showing name, description, allergen tags, and price; and a footer with address and opening hours.
The page must be fully responsive and score above 85 on Lighthouse accessibility.
All images may be placeholders. No JavaScript framework required — plain HTML/CSS or any toolchain is fine.$c$, $c$speed_build$c$, $c$url_submit$c$, $c$medium$c$, 35, $c$javascript$c$, NULL, NULL, NULL, NULL, false),
  ($c$clone-linear-app$c$, $c$Clone the Linear Homepage$c$, $c$Clone the marketing homepage of Linear (linear.app) as closely as possible and deploy it.
Recreate the hero section (headline, subheadline, CTA buttons), the feature highlights section, and the bottom CTA/footer strip.
Match the dark colour scheme, typography weight, spacing, and overall premium feel of the original.
All copy and images may be approximated — pixel perfection is not required, but layout fidelity and visual hierarchy must be close.
Aim for a Lighthouse performance score above 80 and best-practices score above 85.$c$, $c$clone_battle$c$, $c$url_submit$c$, $c$hard$c$, 50, $c$javascript$c$, NULL, NULL, NULL, $c$https://linear.app$c$, false),
  ($c$clone-vercel-homepage$c$, $c$Clone the Vercel Homepage$c$, $c$Clone the Vercel marketing homepage (vercel.com) as faithfully as possible and deploy your version.
Must include: the hero section with headline, animated or gradient accent, and CTA; a 'Deploy with zero config' or equivalent feature section; a social-proof / logo strip; and a footer.
Match Vercel's dark theme, clean typographic hierarchy, and generous whitespace.
Images and copy may be approximated. Score at least 80 on Lighthouse performance.$c$, $c$clone_battle$c$, $c$url_submit$c$, $c$hard$c$, 50, $c$javascript$c$, NULL, NULL, NULL, $c$https://vercel.com$c$, false),
  ($c$clone-stripe-pricing$c$, $c$Clone the Stripe Pricing Page$c$, $c$Clone the Stripe pricing page (stripe.com/pricing) and deploy it.
Recreate the pricing tier cards, the feature comparison table or checklist, and the contact/enterprise section at the bottom.
Match Stripe's clean white layout, card styles, and blue accent colour scheme as closely as possible.
All pricing figures and copy may be approximated or replaced with fictional equivalents.
Target Lighthouse scores: performance above 75, accessibility above 85.$c$, $c$clone_battle$c$, $c$url_submit$c$, $c$medium$c$, 40, $c$javascript$c$, NULL, NULL, NULL, $c$https://stripe.com/pricing$c$, false),
  ($c$clone-raycast-homepage$c$, $c$Clone the Raycast Homepage$c$, $c$Clone the Raycast marketing homepage (raycast.com) and deploy it.
Must include the hero section with product screenshot/mockup, the feature cards section, and at minimum one testimonial or social-proof block.
Raycast uses a dark background with vivid gradient accents — reproduce this visual identity as closely as possible.
Copy and images may be approximated. Aim for Lighthouse performance above 75 and accessibility above 80.$c$, $c$clone_battle$c$, $c$url_submit$c$, $c$hard$c$, 50, $c$javascript$c$, NULL, NULL, NULL, $c$https://raycast.com$c$, false)
ON CONFLICT (slug) DO NOTHING;
